# Generated by Django 5.0.6 on 2024-05-19 13:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.UUIDField(default=uuid.UUID('8d02841a-aa54-4f15-9e1d-a04b4af505b1'), primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100, unique=True)),
                ('author', models.TextField(max_length=100)),
                ('order_link', models.TextField(max_length=2000)),
                ('image_link', models.TextField(max_length=2000)),
            ],
        ),
    ]
